version: '3.5'

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 8SLK3Bny
      MYSQL_DATABASE: tor
    user: ${CURRENT_UID}
    volumes:
      - .:/docker-entrypoint-initdb.d/
      - my-datavolume:/var/lib/mysql
  memcached:
   image: memcached
   ports:
     - "11211:11211"
   entrypoint:
    - memcached
    - -m 64

  proxy:
    image: dperson/torproxy
    restart: always
    ports:
      - 8118:8118
      - 9050:9050
    user: ${CURRENT_UID}

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080
    user: ${CURRENT_UID}
  
  scrapy:
    depends_on:
      - db
      - proxy
      - memcached
    image: fresh/scrapper
    restart: on-failure
    user: ${CURRENT_UID}
    deploy:
      resources:
        limits:
          memory: 2gb
        reservations:
          memory: 500m
    environment:
      LANG: en_US.UTF-8

  isup:
    depends_on:
      - db
      - proxy
      - memcached
    image: fresh/isup
    restart: on-failure
    user: ${CURRENT_UID}
    deploy:
      resources:
        limits:
          memory: 1gb
        reservations:
          memory: 500m
    environment:
      LANG: en_US.UTF-8

  frontend:
    depends_on:
      - db
      - memcached
    image: fresh/frontend
    restart: on-failure
    ports:
      - 5000:5000
    user: ${CURRENT_UID}
    environment:
      LANG: en_US.UTF-8

volumes:
    my-datavolume:

